### ISSUE TITLE
`MessageContent` 的被引用消息指向的是消息本身而不是被引用的消息

### ISSUE THREAD

**Issue by NoMathExpectation** [simple-robot/simbot-component-kook#174]
### 是否会提供贡献？

否

### 版本信息

```kts
// simbot
    val simbotVersion = "4.6.0"
    implementation("love.forte.simbot:simbot-core:$simbotVersion")
    compileOnly("love.forte.simbot.common:simbot-common-annotations:$simbotVersion")
    implementation("love.forte.simbot.component:simbot-component-onebot-v11-core:1.4.0")
    implementation("love.forte.simbot.component:simbot-component-kook-core:4.0.1")
```

### 涉及的编程语言

Kotlin

### 项目构建工具

Gradle

### 内容描述

自己手搓了一个获取被引用的消息的指令，并打印到日志里。
```kt
suspend fun LiteralSelectionCommandNode<AnyExecuteContext>.commandRef() =
    literal("ref")
        .requiresPermission("command.experimental.ref")
        .executes {
            logger.info { it.originalMessage?.referenceMessage?.messages?.toReadableString() }
        }
```
在kook上执行时，打印的却是消息本身：
![image](https://github.com/user-attachments/assets/65a1cb8d-1c0c-4ed9-92d8-963411240775)

![image](https://github.com/user-attachments/assets/9d6cfa6e-2a29-477d-96a4-d69d36770382)

**Comment by ForteScarlet** [comment]
> `logger.info { it.originalMessage?.referenceMessage?.messages?.toReadableString() }`

这里的 `it.originalMessage` 的类型就是对应的 `MessageContent` 是吗

**Comment by NoMathExpectation** [comment]
> > `logger.info { it.originalMessage?.referenceMessage?.messages?.toReadableString() }`
> 
> 这里的 `it.originalMessage` 的类型就是对应的 `MessageContent` 是吗

是的，因为这个指令系统是分析转换为字符串后的消息，所以需要绑定一个对应原始消息方便指令处理

**Comment by ForteScarlet** [comment]
好的。
题外话顺带一提：Kotlin 里按理说应该使用挂起函数 `content.referenceMessage()` 而不是阻塞属性 `content.rferenceMessage`，如果在Kotlin里使用非挂起的属性或函数应当会有警告才对，这些阻塞API都是为了Java而设计的

**Comment by ForteScarlet** [comment]
![image](https://github.com/user-attachments/assets/ed47429c-97fb-4e4a-af69-380694f1c5a1)
没有类似这种的提示吗？

**Comment by NoMathExpectation** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045247/362754310-ed47429c-97fb-4e4a-af69-380694f1c5a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDM3NDAsIm5iZiI6MTcyNDk0MzQ0MCwicGF0aCI6Ii80MDA0NTI0Ny8zNjI3NTQzMTAtZWQ0NzQyOWMtOTdmYi00ZTRhLWFmNjktMzgwNjk0ZjFjNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE0NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MWFhNjFmM2Y2MmJlYWMyZDhkOTEwZGM0ZDNlNmQ1YzNjNjY5YWI4NTY4NDJhMGUxYjhiYTFlNDczMTNmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8N10SajyWGLklNkII90fuOG0cr8mt7o_cRk0mIwt9Kg) 没有类似这种的提示吗？

![image](https://github.com/user-attachments/assets/38e90745-7d9d-46dc-bd2c-aab086aafd37)

**Comment by ForteScarlet** [comment]
怪事，也没有直接通过idea快速修复加上的 `@Opt(Api4J::class)` 吗

**Comment by ForteScarlet** [comment]
好吧，这个问题有空我再看看有没有办法改善吧。不过至少现在你知道了（
可以把这类阻塞属性或阻塞函数都换成对应的挂起API
