### ISSUE TITLE
[Bug]似乎偶尔会出现事件重发的现象

### ISSUE THREAD

**Issue by khjxiaogu** [simple-robot/simbot-component-kook#68]
原因不明，但是会导致短时间内相同信息发送两次。

**Comment by ForteScarlet** [comment]
是否是指定的某种对象的 `sendAsync` （比如只是 `Channel.sendAsync` ）还是存在普遍问题？
出现频率和场景（例如是在某特定的事件类型监听中）是如何的
发生问题时是否有什么共同点？
以及有无出现问题的可复现代码

**Comment by khjxiaogu** [comment]
Channel.sendAsync，偶发性的，没有共同点。
代码仅仅是监听到ChannelMessageEvent的时候产生一个根据message的文字内容进行hash的回复。
在不断测试过程中它会偶尔出现提供一次文本，但是却回复了两个完全相同的hash的情况。

**Comment by ForteScarlet** [comment]
尝试使用其他API（例如 `sendBlocking` ）观察下会存在此问题吗

尝试验证是仅仅消息发送出现重复，还是事件存在重复触发的情况

以及出现的 _偶发性_ 是比较随机的时机还是进行高频消息测试时会出现呢

**Comment by khjxiaogu** [comment]
经过打印测试，似乎是事件重发。偶发性是非常随机的时机，基本上是提供服务的时候偶尔出现。

**Comment by ForteScarlet** [comment]
如果是事件重发的话，那可能性之一是在进行 [reconnect](https://developer.kookapp.cn/doc/websocket#%E4%BF%A1%E4%BB%A4[5]%20RECONNECT) 的时候，事件调度尚未完成，内部记录的 `sn` 值仍未递增导致实现被resume了

需要考虑优化一下

**Comment by ForteScarlet** [comment]
输出 `love.forte.simbot.kook.bot` 和 `love.forte.simbot.kook.bot.client` 的 `TRACE` 级别日志可以看到事件调度、sn记录值等比较详细的日志，在尝试调整之前也可以通过这些日志稍微留意一下

**Comment by ForteScarlet** [comment]
最新的快照版本 [v3.0.0.0-alpha.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/love/forte/simbot/component/simbot-component-kook-core/3.0.0.0-alpha.2-SNAPSHOT/)  内调整了 `sn` 的更新机制，可以刷新快照并再做尝试，观察效果
